version: "3.9"

services:
  frontend:
    image: ghcr.io/blockscout/frontend:${FRONTEND_DOCKER_TAG:-latest}
    pull_policy: always
    platform: ${DOCKER_PLATFORM:-linux/arm64}
    restart: always
    container_name: "frontend"
    environment:
      - HOSTNAME=0.0.0.0
      - PORT=3000
      - NODE_ENV=production
    env_file:
      - ../envs/common-frontend.env
